### ISSUE TITLE
Update component to adhere to Commodore component best practices

### ISSUE THREAD

**Issue by simu** [projectsyn/component-keycloak#198]
## Context

We've documented some best practices for Commodore components regarding how container images and Helm charts should be configured in the component defaults (see https://syn.tools/syn/explanations/commodore-components/container-images.html and https://syn.tools/syn/explanations/commodore-components/helm-charts.html).

The component currently doesn't adhere to the documented best practices.

* Helm chart version specifications use the legacy format which may not be supported in future versions of Commodore Renovate (cf. https://github.com/projectsyn/commodore-renovate/tree/master/src/commodore-helm): https://github.com/projectsyn/component-keycloak/blob/a11a34c2b9c3c68c90537727627b4915382d844b/class/defaults.yml#L42-L44
* The container images are specified partially in the component defaults: https://github.com/projectsyn/component-keycloak/blob/a11a34c2b9c3c68c90537727627b4915382d844b/class/defaults.yml#L162-L164 https://github.com/projectsyn/component-keycloak/blob/a11a34c2b9c3c68c90537727627b4915382d844b/class/defaults.yml#L301-L302

## Proposed changes

Migrate to a component structure which completely adheres to the best practices. This introduces a breaking change because the `charts` parameter structure will change.

Additionally, to make the Renovate PRs for the resulting structure useful, we'll want to add package rules to group the Helm chart and container image versions for Keycloak and PostgresQL respectively.

## Acceptance criteria

* The component defaults adhere to the container image and Helm chart best practices
* New component version is released

## Alternatives

Don't make changes, and accept that this component is different.

**Comment by megian** [comment]
Image versions: #206 206
