### ISSUE TITLE
Postgres statefulset manifest incompatible with K8s >=1.16

### ISSUE THREAD

**Issue by megian** [projectsyn/component-keycloak#23]
The generated `statefulset` for the Postgres DB (Bitnami) does generate a `statefulset` with the apiVersion `apps/v1beta2`. https://kubernetes.io/docs/reference/using-api/deprecation-guide/#statefulset-v116 This causes ArgoCD can not apply the manifest.

## Steps to Reproduce the Problem

  1. Generate the component manifests with v0.7.0 and kapitan 0.29.4

## Actual Behavior
The manifest keycloak/01_keycloak_helmchart/keycloak/charts/postgresql/templates/statefulset.yaml contains the API version `apps/v1beta2``

## Expected Behavior
The manifest keycloak/01_keycloak_helmchart/keycloak/charts/postgresql/templates/statefulset.yaml  should contain `apps/v1` available since K8s 1.9.

**Comment by megian** [comment]
Can potentially be solved with commodore#323.

**Comment by ccremer** [comment]
This has been solved with #41 , provided you'll use the `latest` tag / master branch from commodore, as it's not yet released.
