### ISSUE TITLE
Helm Chart is severely outdated

### ISSUE THREAD

**Issue by mhutter** [projectsyn/component-keycloak#72]
## Steps to Reproduce the Problem

Currently in use: 10.3
Current version: 15.1

https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/Chart.yaml#L3

## Actual Behavior
Things like this:
```
# kubectl -n vshn-keycloak-prod get ingress/keycloak -o yaml | head -n2
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
apiVersion: extensions/v1beta1
kind: Ingress
``` 
## Expected Behavior
Up to date charts

**Comment by ccremer** [comment]
Closed as duplicate of #8
