### ISSUE TITLE
Can't compile the helm chart version 11+

### ISSUE THREAD

**Issue by megian** [projectsyn/component-keycloak#8]
## Context

Looks like the helm chart binding of kapitan is unable to render the postgres 10.x bitnami template:
```
parse error in "keycloak/charts/postgresql/charts/common/templates/_secrets.tpl": template: keycloak/charts/postgresql/charts/common/templates/_secrets.tpl:84: function "lookup" not defined
Compile error: failed to compile target: keycloak
```

See kapicorp/kapitan#647.

**Comment by simu** [comment]
Note: https://github.com/kapicorp/kapitan/pull/647 will probably be closed in favor of https://github.com/kapicorp/kapitan/pull/701

**Comment by mhutter** [comment]
Since commodore 0.11 is now released (with Kapitan 0.30 and hence support for Helm 3) this should now work

**Comment by corvus-ch** [comment]
Relates to #116

**Comment by megian** [comment]
Did an upgrade from `quay.io/keycloak/keycloak:12.0.4` to quay.io/keycloak/keycloak:15.0.2. by changing the component version from v5.2.0 to v6.1.0. Looks everything went well even by skipping major versions.

Database update has been completed:
```
15:08:59,082 INFO  [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] (ServerService Thread Pool -- 69) Updating database. Using changelog META-INF/jpa-changelog-master.xml
15:09:00,477 INFO  [org.hibernate.jpa.internal.util.LogHelper] (ServerService Thread Pool -- 69) HHH000204: Processing PersistenceUnitInfo [
	name: keycloak-default
	...]
```

**Comment by megian** [comment]
Relates to #119

**Comment by megian** [comment]
The database update from Keycloak v15.0.2 to v16.1.1 went well:

```
15:08:59,082 INFO  [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] (ServerService Thread Pool -- 69) Updating database. Using changelog META-INF/jpa-changelog-master.xml
15:09:00,477 INFO  [org.hibernate.jpa.internal.util.LogHelper] (ServerService Thread Pool -- 69) HHH000204: Processing PersistenceUnitInfo [
	name: keycloak-default
	...]
```
